apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-rawabet
spec:
  type: ClusterIP
  selector:
    app: backend-rawabet
  ports:
    - name: http
      port: 8081
      targetPort: 8081
